### ISSUE TITLE
[Feature] Provide deleted status for deleted connectors within connector_status model

### ISSUE THREAD

**Issue by fivetran-joemarkiewicz** [fivetran/dbt_fivetran_log#108]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Currently the Fivetran Log raw data does not provide a deleted status for connectors when they are removed. Therefore, if a connector is deleted it will report as the last known status before it was deleted (ie. paused, broken, etc.). This can lead to confusing results where a connector will be reported as one status, but it will actually be deleted and should be recognized as such. 

This Feature Request is to ensure the `deleted` status may be displayed properly within the `fivetran_platform__connector_status` end model.

### Describe alternatives you've considered

As of know the only alternative is to filter our deleted connectors. I don't feel this is the best option and we should instead still report on these connectors, but mark them accordingly as `deleted`.

### Are you interested in contributing this feature?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by fivetran-jamie** [comment]
i imagine the code change in the connector_status model would look just like our [paused-logic](https://github.com/fivetran/dbt_fivetran_log/blob/main/models/fivetran_platform__connector_status.sql#L104)

but first we'll need to add `_fivetran_deleted` to the staging connector model (it's in the columns [macro](https://github.com/fivetran/dbt_fivetran_log/blob/main/macros/get_brand_columns.sql#L4) but not the [model](https://github.com/fivetran/dbt_fivetran_log/blob/main/models/staging/stg_fivetran_platform__connector.sql) itself)

**Comment by fivetran-joemarkiewicz** [comment]
This has been addressed in the latest release of the Fivetran Log package. Closing out this issue.
