### ISSUE TITLE
[Bug] JSON parsing error in Redshift

### ISSUE THREAD

**Issue by fivetran-reneeli** [fivetran/dbt_fivetran_log#113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Error downstream in `fivetran_platform_connector_status` and  `fivetran_platform_audit_table`  due to the `message_data`  the log [table](https://github.com/fivetran/dbt_fivetran_log/blob/main/models/staging/stg_fivetran_platform__log.sql) getting truncated due to lengthy json value. The incomplete json is causing the model runs to fail.

In order to support these json objects in Redshift the SUPER type is necessary but it is complicated.

As a workaround, we should update in the package to filter `message_data` first for only necessary keys prior to any parsing (event_subtype='status') 

### Expected behavior

json to be parsed correctly and package to run

### dbt Project configurations

na

### Package versions

na

### What database are you using dbt with?

redshift

### dbt Version

na

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-catfritz** [comment]
This has been addressed in release v1.5.0, which is now live on the dbt hub. Closing the issue!
