### ISSUE TITLE
[Feature] Update docs to make clarify sync times 

### ISSUE THREAD

**Issue by fivetran-reneeli** [fivetran/dbt_fivetran_log#128]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

The sync times in FIVETRAN_PLATFORM__AUDIT_TABLE are not the most recent sync times that are found in the source table because we only take record when a table is being written to. See [this CTE](https://github.com/fivetran/dbt_fivetran_log/blob/5fef3647a47e682236713c274895905ec5a81643/models/fivetran_platform__audit_table.sql#L89-L93) in that model that has the event_subtype limiter. 

In conclusion, if there is no corresponding event logged that a table is written to, the sync time doesn't get persisted (that’s why the most recent sync times are present in the staging log table but not in our audit model since we only show the timestamps for when write events occur).

We should make this more clear for the fields in the docs for FIVETRAN_PLATFORM__AUDIT_TABLE related to sync times.

### Are you interested in contributing this feature?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
This has been addressed in the latest v1.8.0 release!
