### ISSUE TITLE
[Version Update] dbt 1.8 introduced renaming of tests to data_tests

### ISSUE THREAD

**Issue by JustMaris** [fivetran/dbt_fivetran_log#133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

As of dbt 1.8, the tests have been renamed to data_tests.
Currently, this means that anyone running dbt 1.8+ will see warning, that tests have been deprecated.
This has been done in other packages, such as dbt_utils, to follow the new format.

### Relevant error log or model output

```shell
12:37:08  [WARNING]: Deprecated functionality
The `tests` config has been renamed to `data_tests`. Please see
https://docs.getdbt.com/docs/build/data-tests#new-data_tests-syntax for more
information.
```

### Expected behavior

tests are named data_tests, and there are no warnings

### dbt Project configurations

None

### Package versions

packages:
  - package: brooklyn-data/dbt_artifacts
    version: [ ">=2.6.0", "<2.7.0" ]
  - package: dbt-labs/dbt_utils
    version: [">=1.1.0", "<1.2.0"]
  - package: fivetran/fivetran_log
    version: [ ">=1.9.0", "<1.10.0" ]

### What database are you using dbt with?

snowflake

### dbt Version

1.8.3

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-reneeli** [comment]
Hi @JustMaris, thanks so much for opening this issue as well as contributing the code!

Our team is aware of this dbt update and will be including this in our next set of releases across all of our packages. We will plan to loop in your contribution when making the update to the Fivetran Log package!

**Comment by fivetran-jamie** [comment]
Hey there @JustMaris -- Looks like dbt labs removed this deprecation warning in [September](https://github.com/dbt-labs/dbt-core/issues/10564) and have decided to stick with `tests`

Can you confirm whether this warning has stopped or persisted for you?

**Comment by JustMaris** [comment]
@fivetran-jamie I don't see it indeed, where the dbt core version has been updated.

Close this to maintain support for pre1.8?

**Comment by fivetran-jamie** [comment]
Nice we'll close this as dbt labs has addressed the deprecation warning themselves, but please feel free to re-open or reach out if you'd like to discuss further
