### ISSUE TITLE
BUG - dbt hub version incompatible with latest dbt_utils

### ISSUE THREAD

**Issue by rcaddell** [fivetran/dbt_fivetran_log#32]
**Are you a current Fivetran customer?** 

Randy Caddell, BI Architect, NWN Carousel 

**Describe the bug**

fivetran_log and fivetran_utils packages out of sync (dbt hub), causing incompatibility with dbt_utils 0.8.0

**Steps to reproduce**
1. Add fivetran_log package to a clean project
2. run dbt deps
3. note versions of packages installed

**Expected behavior**

Expect fivetran_log v0.4.1, fivetran_utils v 0.3.0 and dbt_utils 0.8.0

**Project variables configuration**

vars:
    fivetran_log:
        fivetran_log_database: pc_fivetran_db
        fivetran_log_schema: fivetran_log

**Package Version**

packages:
    - package: fivetran/fivetran_log
      version: [">=0.4.0", "<0.5.0"]

**Warehouse**

 
- [ ] BigQuery
- [ ] Redshift
- [x] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Additional context**
 
dbt hub shows latest version as 0.4.1.  When adding the package, with either 0.4.1 or [">=0.4.0", "<0.5.0"] and running dbt deps it installs:
  fivetran_log 0.4.1
  fivetran_utils 0.2.10
  dbt_utils 0.7.6

When following the fivetran_log hyperlink from dbt hub, it shows an upper limit of <0.3.0 for the fivetran_utils package, so the latest fivetran_utils is not installed.  Appears 0.3.0 of fivetran_utils has the updated versions of dbt_utils but 0.2.x has an upper limit of <0.8.0.  

url from dbt hub
https://github.com/fivetran/dbt_fivetran_log/tree/v0.4.1/

Noticed this during testing to upgrade to dbt 1.x

**Screenshots**

**Please indicate the level of urgency** 

This is just a heads up.  It looks like there is just an update needed on the dbt hub site maybe?
**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [x] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [ ] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @rcaddell we have a [pre-release version](https://hub.getdbt.com/fivetran/fivetran_log/0.5.0-b1/) of the `dbt_fivetran_log` package that you can use which is dbt v1.0.0 and dbt-utils 0.8.0 compatible! Feel free to install the pre-release version using the below config in your `packages.yml`:
```yml
packages:
  - package: fivetran/fivetran_log
    version: 0.5.0-b1
```

We are currently working on some major performance updates to the fivetran_log dbt package which is why we have not cut an official release yet. You can expect to see this official release in the next few days. In the meantime the pre-release version should resolve these issues! 😄

**Comment by rcaddell** [comment]
excellent, thanks @fivetran-joemarkiewicz

**Comment by fivetran-joemarkiewicz** [comment]
Happy to help! I will close this issue since we were able to resolve the dependency issue with the pre-release version on the hub.

Be sure to follow this repo or keep an eye on the hub for when we release the official compatibility version!
