### ISSUE TITLE
[Bug] Unique combo of columns test failure due to non JSON in JSON column

### ISSUE THREAD

**Issue by cjjohanson** [fivetran/dbt_fivetran_log#45]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

We have dbt tests failing for a unique_combination_of_columns_test with the following error message:

> Failure in test dbt_utils_unique_combination_of_columns_fivetran_log__schema_changelog_connector_id__destination_id__created_at (models/fivetran_log.yml)

I looked at the results of the following test artifact associated with the error:

> with validation_errors as (

    select
        connector_id, destination_id, created_at
    from ANALYTICS.PUBLIC_fivetran_log.fivetran_log__schema_changelog
    group by connector_id, destination_id, created_at
    having count(*) > 1

)

select *
from validation_errors
;

You can see the results in test_failure_results.csv. I then did some digging where debugging.csv is a snapshot of some of the errors in test_failure_results.csv and I ran the query below to get the results:

> select *
from ANALYTICS.PUBLIC_fivetran_log.fivetran_log__schema_changelog
where
connector_id = 'logic_exporting'
and destination_id = 'wick_crumpet'
and created_at = '2022-03-31 15:02:43.053 +0000'

Looking at debugging.csv, you see from the results that the duplication is happening because fivetran is trying to do the same thing twice and simultaneously. When comparing the message_data column, the same column is being added to the same column at the same time.

Is this a problem on the side of the package? Do you know why this is happening?

[test_failure_results.csv](https://github.com/fivetran/dbt_fivetran_log/files/8413210/test_failure_results.csv)
[debugging.csv](https://github.com/fivetran/dbt_fivetran_log/files/8413212/debugging.csv)

### Relevant error log or model output

```shell
09:37:25  Completed with 1 error and 8 warnings:
09:37:25  
09:37:25  Failure in test dbt_utils_unique_combination_of_columns_fivetran_log__schema_changelog_connector_id__destination_id__created_at (models/fivetran_log.yml)
09:37:25    Got 6 results, configured to fail if != 0
09:37:25  
09:37:25    compiled SQL at target/compiled/fivetran_log/models/fivetran_log.yml/dbt_utils_unique_combination_o_a484aa854783c3b3614d0db8c28551e9.sql
```

### Expected behavior

I would expect the fivetran package to not try to use two different pathways to make one change to a table nor for those two different pathways to occur simulteaneously.

### dbt Project configurations

vars:
  fivetran_log:
    # Link to the package that relies on these vars:
    # https://hub.getdbt.com/fivetran/fivetran_log/latest/
    fivetran_log_database: raw
    fivetran_log_schema: fivetran_logs

  fivetran_log:
    # Explicitly excluding because the runtime of this model is extremely slow,
    # it's taken as long as 14 minutes to build this one table. We don't use 
    # this model, therefore there's no reason to slow down build time for it
    fivetran_log__audit_table:
      +enabled: false 

### Package versions

packages:
  - package: dbt-labs/dbt_utils
    version: 0.8.0

  - package: dbt-labs/segment
    version: 0.7.0

  - package: fivetran/fivetran_log
    version: 0.5.0

  - package: fivetran/salesforce_source
    version: 0.4.1

  - package: fivetran/salesforce
    version: 0.5.1

  - package: fivetran/jira
    version: 0.7.0

  - package: calogica/dbt_date
    version: 0.5.2

  - package: entechlog/dbt_snow_mask
    version: 0.1.6

  - package: fivetran/github
    version: 0.4.0

  - package: fivetran/github_source
    version: 0.4.1
  
  - package: tnightengale/dbt_meta_testing
    version: 0.3.5

### What database are you using dbt with?

snowflake

### dbt Version

Running with dbt=1.0.4

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @cjjohanson thanks so much for the detailed writeup and for opening this issue.

This issue looks pretty familiar to Issue #42 where the uniqueness test is failing. The end result was found to be an issue on the connector side that has since been remedied. Would you be able to update your `dbt_fivetran_log` package to the latest version `0.5.3` and attempt to resync your Fivetran Log connector data.

After doing so, would you be able to let me know if the issue you are seeing still persists? Thanks so much!

**Comment by rcaddell** [comment]
Hello @fivetran-joemarkiewicz, I was experiencing the same error as here and in #42 and after a resync am now experiencing #46.

**Comment by cjjohanson** [comment]
Hey @fivetran-joemarkiewicz, thanks for the response!

I updated the fivetran_log package to 0.5.3 and the error went away. For the sake of clarity around your response, when you say "attempt to resync your Fivetran Log connector data," do you mean to re-sync all historical data specifically for the fivetran_logs connector? I'm a little hesitant to do that because of the monetary/time cost associated with it so I wanted to get a better understanding of the reasoning before I do it. In short: is the re-sync necessary given the error went away?

Now that the original error went away, it has been replaced with the error in [#46](https://github.com/fivetran/dbt_fivetran_log/issues/46) which echoes what @rcaddell said. In my particular situation, the error says:

> 100069 (22P02): Error parsing JSON: unknown keyword "beseeching_spring", pos 18

I did some digging and beseeching_spring is indeed in the message_data column, but it is not a JSON object. It is an object that looks something akin to "beseeching_spring([data in here])" so I think it is failing because it is trying to parse a JSON object that is malformed.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @cjjohanson thanks for the additional context and for sharing your updates!

In response to the full re-sync question, this is something you for sure want to take into consideration when working on all other Fivetran connectors. Thankfully though the Fivetran Log connector is free and you won't need to worry about the cost of the re-sync if you were to kick it off. Additionally, connecting with your account rep on this is always a great place to go as well for confirmation on this matter.

In regards to the new issue you are seeing. It seems that another customer within Issue #46 is experiencing the same error. Would you be able to attempt the hotfix branch I shared and let me know if you still see the issue persist? You can leverage the hotfix branch by using the below config in your `packages.yml`:
```yml
packages:
    - git: https://github.com/fivetran/dbt_fivetran_log.git
      revision: fivetran-joemarkiewicz-patch-1
      warn-unpinned: false
```

Let me know if this works for you. It seems to have worked for the OP from the ticket linked above, and I am currently working on a more permanent solution.

**Comment by cjjohanson** [comment]
Hi @fivetran-joemarkiewicz!

Thank you for clarifying the full-sync question.

I used the hotfix to address the problem within issue [#46](https://github.com/fivetran/dbt_fivetran_log/issues/46) and the result brought me back to the original error that this issue addressed for the unique combination of columns test.

What are the recommended next steps?

**Comment by fivetran-joemarkiewicz** [comment]
Hi @cjjohanson thanks for that clarification!

If that is the case that you are still seeing the uniqueness test fail, then I believe this may be a case of the dbt package failing successfully and we need to dig into why these records are not unique within the connector.  The next step here would be to open a [Fivetran Support Ticket](https://support.fivetran.com/hc/en-us) so members of our product and engineering teams may be able to help you further with the connector.

Let me know if you have any questions.
Thanks!

**Comment by cjjohanson** [comment]
Thank you @fivetran-joemarkiewicz for the help! I just submitted a Fivetran Support ticket [here](https://support.fivetran.com/hc/en-us/requests/82952). I included a link to the ticket just in case.

Thanks again and happy Friday!

**Comment by mauricio-goncales-nativecos** [comment]
Hey, @cjjohanson 
Did you get any response from the Fivetran team?
I'm facing the same error.

**Comment by cjjohanson** [comment]
@mauricio-goncales-nativecos the Fivetran team is currently working on it but I have not heard from them in 2 days, so I sent them a gentle nudge to see what's going on.

@fivetran-joemarkiewicz does testing this out consist of the same process regarding the hotfix branch you mentioned the other day?

**Comment by fivetran-joemarkiewicz** [comment]
Hey @cjjohanson, yup testing this out will just require you to use the below config in your `packages.yml` and rerun `dbt deps` and the execute your `dbt run` and `dbt test`. Note that a full resync **is not needed** to test this.

```yml
packages:
  - git: https://github.com/fivetran/dbt_fivetran_log.git
    revision: fivetran-joemarkiewicz-patch-1
    warn-unpinned: false
```

**Comment by adrian5991** [comment]
Hey @fivetran-joemarkiewicz just to add another data point I've been experiencing the same test failure and using your branch has seemed to resolve the issue.

Should we continue to use this branch or will the main package be updated soon?

**Comment by fivetran-joemarkiewicz** [comment]
That's great to hear to @adrian5991 and thanks for jumping in!

I would recommend using the current branch for now. The current branch is not something I would like to push to a release yet as it is pretty rigid in fixing this one issue. I would like to do some further testing to ensure I cover all our bases before we release an official fix.

I will be on PTO the remainder of the week so you can realistically expect an official fixed release mid/late next week. In the meantime, I will not change the current branch I have and you are welcome to use it until the official release is live.

**Comment by mauricio-goncales-nativecos** [comment]
Hey, @fivetran-joemarkiewicz  with the release I was able to run the job with success.
Thanks for that

**Comment by cjjohanson** [comment]
@fivetran-joemarkiewicz I know you're on PTO (have fun!) but I did just noticed something that I wanted to clear up.

I'm unsure which branch to use. Here is the branch that you most recently recommended:
packages:
  - git: https://github.com/fivetran/dbt_fivetran_log.git
    revision: fivetran-joemarkiewicz-patch-1
    warn-unpinned: false
which is the same as you mentioned in an earlier comment and am currently using. I went to [#49 (https://github.com/fivetran/dbt_fivetran_log/issues/49) and saw a different hotfix that you posted:
> packages:
>   - git: https://github.com/fivetran/dbt_fivetran_log.git
>     revision: testfix/adjusted-schema-test
>     warn-unpinned: false
which hotfix are you recommending right now? Just want to be extra sure!

**Comment by JoeMark17** [comment]
Of course, happy to clarify! 

The fivetran-joemarkiewicz-patch-1 branch includes the fix for the schema test update **and** removes the non JSON data from the transformation logs. 

If you were having the JSON parse error before, then I would recommend using the fivetran-joemarkiewicz-patch-1 branch for the meantime since it solves both the JSON error and updates the schema test.

I hope this helps!

**Comment by fivetran-joemarkiewicz** [comment]
Hi All,

The above PR is open for review and I hope we will be able to get a release out early this week. In the meantime, feel free to test out the changes within the following branch.
```yml
packages:
  - git: https://github.com/fivetran/dbt_fivetran_log.git
    revision: bugfix/transformation-log-and-changelog-test
    warn-unpinned: false
```
This branch fixes a schema test within the `fivetran_log__schema_changelog` model as well as filtering out transformation logs within the `fivetran_log__connector_status models`. 

Let me know if you have any questions and I hope we will be able to cut a release with these updates soon!

**Comment by cjjohanson** [comment]
@fivetran-joemarkiewicz hi! I've gone through the error logs for our dbt cloud jobs and can happily using "fivetran-joemarkiewicz-patch-1" looks to have resolved the problem. I don't see any errors related to the malformed JSON or duplicate row count!

Should I stay with fivetran-joemarkiewicz-patch-1 until you're able to cut a release with the updates? Or should I move from fivetran-joemarkiewicz-patch-1 to bugfix/transformation-log-and-changelog-test?

**Comment by fivetran-joemarkiewicz** [comment]
Hi @cjjohanson I will be cutting the release later today so hopefully you can move off the branches by EOD.

I made a few minor updates to the `bugfix/transformation-log-and-changelog-test` branch to make the package a bit more dynamic. If you wanted to test that out you are more than welcome to as that is the branch that will be merged for the release later today.

**Comment by fivetran-joemarkiewicz** [comment]
Hi All! 

I sincerely appreciate your patience while we developed the adjustments within the package to account for the bug mentioned in this ticket. I was just able to cut the latest release of the dbt_fivetran_log `v0.5.4` package which applies a bugfix to account for the issue detailed in this ticket.

The `v0.5.4` release should be live on the dbt hub at the top of the hour. I will be closing this issue as the latest release should resolve this issue. Please feel free to comment in this issue, or open a new one, if you encounter any questions in the latest release.

Thanks for all your help in identifying and resolving this issue! 🎉

**Comment by adrian5991** [comment]
Hey @fivetran-joemarkiewicz, appreciate the work you've done for this issue!

We're now seeing a similar error when the `message_data` field is included in the test: 
```
Failure in test dbt_utils_unique_combination_of_columns_fivetran_log__schema_changelog_connector_id__destination_id__message_data__created_at
```

The rows causing the failure look like:
```tsv
CONNECTOR_ID	CONNECTOR_NAME	DESTINATION_ID	DESTINATION_NAME	CREATED_AT	EVENT_SUBTYPE	MESSAGE_DATA	TABLE_NAME	SCHEMA_NAME
gift_rousing	fivetran_salesforce	sucrose_bravely	Snowflake_CA	2022-04-16 00:34:30.784	alter_table	{"type":"DROP_COLUMN","table":"ironclad_ironclad_contract_c","properties":{"columnName":"minimum_bundle_p-deprecated-03c5e565-254f-4c00-a3ac-22d8af1ea63b"}}	"ironclad_ironclad_contract_c"	
gift_rousing	fivetran_salesforce	sucrose_bravely	Snowflake_CA	2022-04-16 00:34:30.784	alter_table	{"type":"DROP_COLUMN","table":"ironclad_ironclad_contract_c","properties":{"columnName":"minimum_bundle_p-deprecated-03c5e565-254f-4c00-a3ac-22d8af1ea63b"}}	"ironclad_ironclad_contract_c"	
```

Is this still a problem on the package side?
