### ISSUE TITLE
number_of_api_calls zero in connector_daily_api_calls

### ISSUE THREAD

**Issue by milancermak** [fivetran/dbt_fivetran_log#7]
Hi all,

I've added this dbt module to my project so I can build a monitoring dashboard in Looker. I've stumbled on some weird issue where the daily api calls table is reporting zeros from mid-November.

I've tried to find a culprit, but didn't manage. When I run just the [query counting the API calls](https://github.com/fivetran/dbt_fivetran_log/blob/master/models/fivetran_log_connector_daily_api_calls.sql#L7-L21), I get non-zero numbers in the `number_of_api_calls` column. I'm guessing the zeros come from [here](https://github.com/fivetran/dbt_fivetran_log/blob/master/models/fivetran_log_connector_daily_api_calls.sql#L69-L72) but I'm really not sure.

Any ideas what might be wrong?

**Comment by milancermak** [comment]
Ah, nevermind, was some deployment related problem.

**Comment by milancermak** [comment]
Ah, sorry, I spoke too soon. I was looking at a wrong table. The issue is still there, 0 api calls since mid November 🤷

**Comment by fivetran-jamie** [comment]
hey there! sorry for the delay on this 😬 

Would you mind sharing screenshots of the different results you're seeing from the query vs the model?

**Comment by fivetran-kristin** [comment]
Closing this issue for now, as we haven't heard back.  @milancermak if this issue persists, please create a new issue and we'll dig in.
